// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package rent

// Injectors from wire.go:

func InitializeRentController() *RentController {
	rentRepository := NewRentRepository()
	domainRentService := NewRentService(rentRepository)
	rentController := NewRentController(domainRentService)
	return rentController
}
