// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package user

// Injectors from wire.go:

func InitializeUserController() *UserController {
	userRepository := NewUserRepository()
	domainUserService := NewUserService(userRepository)
	userController := NewUserController(domainUserService)
	return userController
}
