// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package vehicles

// Injectors from wire.go:

func InitializeVehicleController() *VehicleController {
	vehicleRepository := NewVehicleRepository()
	domainVehicleService := NewVehicleService(vehicleRepository)
	vehicleController := NewVehicleController(domainVehicleService)
	return vehicleController
}
